schema {
    query: Query
}

type Query {
    team(abbr: String!): Team
    teams: [Team]
    champ(slug: String!): Champ
    champs: [Champ]
}

type Team {
    name: String!
}

type Champ {
    name: String!
}
