schema {
    query: Query
}

type Query {
    team(abbr: String!): Team!
    teams: [Team!]!
    champ(slug: String!): Champ!
    champs: [Champ!]!
}

type Champ {
    slug: String!
    name: String!
}

type Team {
    abbr: String!
    name: String!
    full_name: String!
    trophies: [Trophy!]!
}

type Trophy {
    year: Int!
    champ: Champ!
}