app:
  name: "gorduchinha"
  debug: false

cache:
  db: 0
  prefix: "gorduchinha"
  default-expiration: "24h"

server:
  prefix: "/api/v1"
  max-requests-per-second: 10
  auth:
    clients-urls:
      - "*"

log:
  log-to-file: false

http-client:
  timeout: "60s"
