app:
  name: "gorduchinha"

db:
  url:

cache:
  url:
  db: 0
  prefix: "gorduchinha"
  default-expiration: "24h"

server:
  port:
  prefix: "/api/v1"
  auth:
    clients-urls:
      - "https://classicos.info"
  rate-limit:
    period: "1s"
    limit: 10
  route-keys:
    update-trophies:

http-client:
  timeout: "60s"
