app:
  name: "gorduchinha"

db:
  host:
  port:
  user:
  pass:
  name:

cache:
  host:
  port:
  user:
  pass:
  db: 0
  prefix: "gorduchinha"
  default-expiration: "24h"

server:
  port:
  prefix: "/api/v1"
  max-requests-per-second: 10
  auth:
    clients-urls:
      - "https://classicos.info"

log:
  log-to-file: false

http-client:
  timeout: "60s"
