app:
  name: "gorduchinha"
  debug: true

db:
  host:
  port:
  user:
  pass:
  name:

cache:
  host:
  port:
  user:
  pass:
  db: 0
  prefix: "gorduchinha"
  default-expiration: "24h"

server:
  port: 8080
  prefix: "/api/v1"
  max-requests-per-second: 10
  auth:
    clients-urls:
      - "*"

log:
  log-to-file: false

http-client:
  timeout: "60s"
